services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: xxbruij
      MYSQL_DATABASE: finances
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://root:xxbruij@db:3306/finances"
      PORT: 3001
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
volumes:
  mysql_data: